kind: pipeline
type: docker
name: default

steps:

  - name: build-backend
    image: eclipse-temurin:17-jdk
    commands:
      - chmod +x gradlew
      - ./gradlew test bootJar

  - name: sync-reports
    image: alpine:3.16.0
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: offshore-safety-directive-builds
      template: "*{{build.status}}* <{{build.link}}|Commit {{truncate build.commit 7}} on {{build.branch}} by ${DRONE_COMMIT_AUTHOR_NAME}>\nReports published to: http://drone-assets.fivium.local:9090/offshore-safety-directive/{{build.number}}/"
    when:
      status: [ success, failure ]


volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/offshore-safety-directive