kind: pipeline
type: docker
name: default

steps:

  - name: build-backend
    image: eclipse-temurin:17-jdk
    commands:
      - chmod +x gradlew
      - ./gradlew test bootJar

  - name: sync-reports
    image: alpine:3.16.0
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

  - name: publish-docker-develop
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/offshore-safety-directive
      tags:
        - develop
      config:
        from_secret: docker_config
    when:
      branch:
        - develop
      status:
        - success

  - name: publish-docker
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/offshore-safety-directive
      tags:
        - ${DRONE_BRANCH/\//-}-${DRONE_BUILD_NUMBER}
      config:
        from_secret: docker_config
    when:
      branch:
        - main
        - hotfix/**
        - release/**
      status:
        - success

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: offshore-safety-directive-builds
      template: "*{{build.status}}* <{{build.link}}|Commit {{truncate build.commit 7}} on {{build.branch}} by ${DRONE_COMMIT_AUTHOR_NAME}>\nReports published to: http://drone-assets.fivium.local:9090/offshore-safety-directive/{{build.number}}/"
    when:
      status: [ success, failure ]


volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/offshore-safety-directive

---

kind: secret
name: docker_config
data: eI0qyNsDUizFXZ6PV/b/pKsVm/v27X0bTeEVkvnUKlXBTPll0L3aYawWuqyDzQJmpppt5CJrykjJgmLaDLAhepSxFUBud2kp6c1+S2YbVD3RKl8RCP3NfV3mgAPInewN6ohGRKlEvT/mc2xY559P/XpiEXS9OSwWgz8r9og/ZVpq9eKMv++aRJOoTwEq2tH0dt2pr+e3dN2JJG6iQSJPnhjzade2gbx7WTQa1gAWw/Xmji1fgatP1EzS9cC2Ua68vkV/G9B0pI6BZJHUSXTxhbWZNgeYpQ3rn6zKPuaoIM9vShWea4Ny/9vN5rpRGpN/oW0aduKlWdBoLvO4E2LTqfOaa4pO+OWxE7xD6LURpo+aKQKnxLhiYN+MYE3T1yb3w7j9uaoTPEeIJrRj19A=
