version: '3.9'

services:

  db:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: osd

volumes:
  db-volume: