<#assign FULL_COLUMN = "FULL_COLUMN" />
<#assign ONE_HALF_COLUMN = "ONE_HALF_COLUMN" />
<#assign ONE_THIRD_COLUMN = "ONE_THIRD_COLUMN" />
<#assign TWO_THIRDS_ONE_THIRD_COLUMN = "TWO_THIRDS_ONE_THIRD_COLUMN" />
<#assign ONE_QUARTER = "ONE_QUARTER" />
<#assign TWO_THIRDS_COLUMN = "TWO_THIRDS_COLUMN" />
<#assign FULL_PAGE = "FULL_PAGE" />