package uk.co.nstauthority.offshoresafetydirective.teams.permissionmanagement;

public enum RolePermission {

  GRANT_ROLES,
  VIEW_ALL_NOMINATIONS,
  VIEW_NOMINATION,
  MANAGE_CONSULTEE_TEAMS,
  MANAGE_INDUSTRY_TEAMS,
  CREATE_NOMINATION,
  EDIT_NOMINATION,
  SUBMIT_NOMINATION,
  MANAGE_NOMINATIONS,
  MANAGE_APPOINTMENTS
}
